<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Smartphone POCO M3 Pro 5G, 6.5, 4GB, 64_76fa85</name>
   <tag></tag>
   <elementGuidId>c3019da8-e909-4c56-96ab-b70cb7639ba1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ui-id-17']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-17 > div.content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>123e276c-c754-4055-b5ae-971e4b35805e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>content</value>
      <webElementGuid>3b2b9608-803a-4ac9-b8a2-4595617132a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Smartphone POCO M3 Pro 5G, 6.5&quot;, 4GB, 64GB, Android 11, crni040.100.908207,99 € (1.567,10 kn)</value>
      <webElementGuid>9c00a2ba-a95d-4960-9fe4-45d462e07648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-17&quot;)/div[@class=&quot;content&quot;]</value>
      <webElementGuid>0048a4fe-8e93-44e9-bb01-ca5569f792e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='ui-id-17']/div</value>
      <webElementGuid>51ce92f4-3de1-4f21-aed9-e4ec9d2fe84d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[2]/following::div[18]</value>
      <webElementGuid>d8c1465e-f972-47ce-acf1-bc046920b210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='U REDU'])[1]/following::div[22]</value>
      <webElementGuid>161142f5-25f7-4b35-a754-578c267c135e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a/div</value>
      <webElementGuid>02a95ccc-2f77-45e7-a3a7-ff1476a61a40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Smartphone POCO M3 Pro 5G, 6.5&quot;, 4GB, 64GB, Android 11, crni040.100.908207,99 € (1.567,10 kn)' or . = 'Smartphone POCO M3 Pro 5G, 6.5&quot;, 4GB, 64GB, Android 11, crni040.100.908207,99 € (1.567,10 kn)')]</value>
      <webElementGuid>c4807023-e3f6-4ebf-a3e2-da0effde2581</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
