<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Loe_AddProductReview.Rating</name>
   <tag></tag>
   <elementGuidId>b820b744-e53c-46aa-aa70-b39d78f787c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='AddProductReview_Rating'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4b5661e8-271e-4009-ba3d-8ed4454113d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AddProductReview_Rating</value>
      <webElementGuid>e83ecf03-4b36-4632-94c4-1855f9a334e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AddProductReview.Rating</value>
      <webElementGuid>0041f3f6-45c8-4059-84a0-79e7de709ad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>48edb34c-b18d-47ac-9eff-324d488999d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>9139406a-bc83-48b5-ad06-c095754f8822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;review-form&quot;)/div[@class=&quot;form-fields&quot;]/div[@class=&quot;review-rating&quot;]/ul[1]/li[2]/input[@id=&quot;AddProductReview_Rating&quot;]</value>
      <webElementGuid>6e364a63-55e8-4588-8403-3f42d69c8fba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='AddProductReview_Rating'])[3]</value>
      <webElementGuid>fadf6320-b544-4674-b7a3-5634c9891e41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='review-form']/div[3]/div[3]/ul/li[2]/input[3]</value>
      <webElementGuid>e3841c08-1740-4305-9d8a-4d2df05b9b01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>43b80de3-24ee-4986-9ce2-6d833a799e5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AddProductReview_Rating' and @name = 'AddProductReview.Rating' and @type = 'radio']</value>
      <webElementGuid>8ee6e464-1f18-4b60-87fd-3d3afadc639d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
