<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Recenzija naslova_AddProductReview.Title</name>
   <tag></tag>
   <elementGuidId>7ce321c5-70b2-4b2e-a9be-43be6fd393a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AddProductReview_Title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AddProductReview_Title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>060ae317-e5fa-41f1-8934-37a9e4b4432d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>review-title</value>
      <webElementGuid>46b3e3b9-8c97-4ce2-a259-900ca1eb4e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AddProductReview_Title</value>
      <webElementGuid>84de5075-3cd0-43b1-a594-8c60ea0718df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AddProductReview.Title</value>
      <webElementGuid>a73c1935-6b23-449d-9ee4-9a0dba5baf33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9fbae42b-2641-49ce-bf35-429e6b7e64ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AddProductReview_Title&quot;)</value>
      <webElementGuid>91067e26-d812-4962-a2a4-51b826a6fe00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AddProductReview_Title']</value>
      <webElementGuid>d6a7e43a-6b2f-4906-94e4-633e0097d079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='review-form']/div[3]/div/input</value>
      <webElementGuid>3aa3b620-14dd-4320-9f4f-8dde8f87ff86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>413cda1c-8362-48ef-8d36-52610fc86c5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AddProductReview_Title' and @name = 'AddProductReview.Title' and @type = 'text']</value>
      <webElementGuid>ffcb4b0d-bf56-4380-84b8-9b0edba9dcf7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
