<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Recenzija teksta_AddProductReview._6e9ebe</name>
   <tag></tag>
   <elementGuidId>d1ecf859-b4b9-4a56-a8bf-fd2fb4c0cf30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='AddProductReview_ReviewText']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AddProductReview_ReviewText</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>62f3e23e-2fdd-4a42-b945-78bdd1ad76f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>review-text</value>
      <webElementGuid>093ea9a7-d35c-4f52-bd20-2d7f70defbc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>012a52f5-714a-494d-a8f2-ead1eb5c46ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AddProductReview_ReviewText</value>
      <webElementGuid>83ed0ad3-5450-4ab4-9981-f0d1f7199eab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AddProductReview.ReviewText</value>
      <webElementGuid>83e7c9e4-faa4-4e03-b725-b7d65d83a0ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>2c0e6894-5cce-4823-9c38-1712148c052b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AddProductReview_ReviewText&quot;)</value>
      <webElementGuid>62c5d020-2b92-4ff2-b67c-a0196e56c768</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='AddProductReview_ReviewText']</value>
      <webElementGuid>06963e12-926d-4bc0-b4c8-86ca33ad0880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='review-form']/div[3]/div[2]/textarea</value>
      <webElementGuid>78633235-6cde-4e4c-a3d3-ddc7c1993ed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>90698d8a-6462-48e9-bd48-e7cdf5619437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'AddProductReview_ReviewText' and @name = 'AddProductReview.ReviewText']</value>
      <webElementGuid>cfc89e47-84d6-43d2-9462-621fb6f54326</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
