<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Mjesecsijeanjveljaaoujaktravanjsviba_867e78</name>
   <tag></tag>
   <elementGuidId>9b6d7e55-9b94-4df4-aea9-bbef828b9942</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='DateOfBirthMonth']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;DateOfBirthMonth&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>79388e65-ee5f-4c33-be06-4dec752eaea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DateOfBirthMonth</value>
      <webElementGuid>8038f712-e302-4314-883f-0a2bff74843b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mjesecsiječanjveljačaožujaktravanjsvibanjlipanjsrpanjkolovozrujanlistopadstudeniprosinac</value>
      <webElementGuid>6050c61d-99b7-4219-8b7f-788df731146a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;k-webkit k-webkit114 js no-touch svg inlinesvg svgclippaths&quot;]/body[@class=&quot;color-neutral notAndroid23&quot;]/div[@class=&quot;master-wrapper-page&quot;]/div[@class=&quot;master-wrapper-content&quot;]/div[@class=&quot;master-wrapper-main&quot;]/div[@class=&quot;center-2b&quot;]/form[1]/div[@class=&quot;page registration-page&quot;]/div[@class=&quot;customer-blocks&quot;]/div[@class=&quot;fieldset&quot;]/div[@class=&quot;form-fields&quot;]/div[@class=&quot;inputs left&quot;]/select[2]</value>
      <webElementGuid>de9c5b7b-a018-428f-9241-350b7c9ae8e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='DateOfBirthMonth']</value>
      <webElementGuid>5c60802b-04fc-4c69-8bb8-eeca837f2702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Datum rođenja:'])[1]/following::select[2]</value>
      <webElementGuid>ebd6f44d-b92d-4fbd-a282-f9b56d8d5259</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prezime:'])[1]/following::select[2]</value>
      <webElementGuid>08a86d15-e756-4fa9-8f9f-768469bc9134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Elektronska pošta:'])[1]/preceding::select[2]</value>
      <webElementGuid>ead1822f-6d0e-4c4d-8735-e9cce7e740f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vaša adresa'])[1]/preceding::select[2]</value>
      <webElementGuid>bc680d36-1b4a-4ba2-bd1e-632d958bff21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[2]</value>
      <webElementGuid>28eed5d5-fa25-43e8-96ab-7ebbb064a313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'DateOfBirthMonth' and (text() = 'Mjesecsiječanjveljačaožujaktravanjsvibanjlipanjsrpanjkolovozrujanlistopadstudeniprosinac' or . = 'Mjesecsiječanjveljačaožujaktravanjsvibanjlipanjsrpanjkolovozrujanlistopadstudeniprosinac')]</value>
      <webElementGuid>28860a33-9f19-4a49-a3fb-52ea5ef78c02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
