<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MacBook Air laptopi_add-to-wishlist-b_9b7a7e</name>
   <tag></tag>
   <elementGuidId>a26ae8f6-6137-4497-aac0-6d4df3e1b87d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='add-to-wishlist-button-111052']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#add-to-wishlist-button-111052</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4b503de0-b71f-4d08-9066-7abd8032e38d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e10386df-1ce0-45bd-918e-03dbbcb62580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add-to-wishlist-button-111052</value>
      <webElementGuid>83a58d02-a16e-4d7e-984e-0c6252dbb06a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>add-to-wishlist-button</value>
      <webElementGuid>8c17da3d-70e1-4afe-9f80-993e60e5bc1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-productid</name>
      <type>Main</type>
      <value>111052</value>
      <webElementGuid>4c34245e-da1c-4673-b736-caa379f59313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>AjaxCart.addproducttocart_details('/hr/addproducttocart/details/111052/2', '#product-details-form');return false;</value>
      <webElementGuid>3e10801c-9198-4371-a5d5-d8c59a31f0c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-to-wishlist-button-111052&quot;)</value>
      <webElementGuid>ef27a174-d1c1-454e-ae9d-ad0dec73093b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='add-to-wishlist-button-111052']</value>
      <webElementGuid>95996022-caac-4857-bfb6-ac5011daf40c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/input</value>
      <webElementGuid>9fedbed5-c6a5-41e0-a7c7-62f29f43a8f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'add-to-wishlist-button-111052']</value>
      <webElementGuid>06c61695-4f3a-411e-9a07-e465a8d3cac3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
