<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_vie o proizvodu</name>
   <tag></tag>
   <elementGuidId>4fc912ac-dd2c-48bb-85d2-c11afaa617f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='product-details-form']/div[2]/div/div[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.link-to-product-page</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>12d28d95-74b0-457a-a017-8c32226cebc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/hr/laptop-apple-macbook-air-13-3-retina-mgn63cr-a-octacore-apple-m1-8gb-256gb-ssd-apple-graphics-hr-tipkovnica-sivi-015800376</value>
      <webElementGuid>5e162c5d-f0f0-40a2-8821-89ea7f5e598c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link-to-product-page</value>
      <webElementGuid>1feeb20c-5d56-4113-bbb2-f0d4fcabd3d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>više o proizvodu </value>
      <webElementGuid>3a1ae37d-f076-4f6e-a8a3-d1c04237d80b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-details-form&quot;)/div[@class=&quot;product-content&quot;]/div[@class=&quot;gallery&quot;]/div[@class=&quot;links-panel&quot;]/a[@class=&quot;link-to-product-page&quot;]</value>
      <webElementGuid>4488ac1f-3b54-4b35-9fbb-74c5a1166563</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product-details-form']/div[2]/div/div[3]/a</value>
      <webElementGuid>daa565ae-0409-4725-ad50-8afe9a73e427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'više o proizvodu')]</value>
      <webElementGuid>5a6b97c7-d74a-4c9f-927c-fb516d417c83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[2]/following::a[5]</value>
      <webElementGuid>170ca267-21df-4795-8171-5d1b3f0f5421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='U REDU'])[1]/following::a[6]</value>
      <webElementGuid>ebbd3677-3fe8-458a-a9de-6fe0c2b2a708</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detalji'])[1]/preceding::a[1]</value>
      <webElementGuid>06dc3dfd-975c-403f-ae98-763b30ab8540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Šifra:'])[1]/preceding::a[1]</value>
      <webElementGuid>b4c23a8a-5dc0-49bd-8434-1f13d2c6586f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='više o proizvodu']/parent::*</value>
      <webElementGuid>597e5bfa-438a-4527-879f-c794d829dbe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/hr/laptop-apple-macbook-air-13-3-retina-mgn63cr-a-octacore-apple-m1-8gb-256gb-ssd-apple-graphics-hr-tipkovnica-sivi-015800376')])[3]</value>
      <webElementGuid>1b98d02b-efcb-45b9-96eb-fdfdadc12f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>9ed09c39-e7ab-484d-bd83-b2ec317b7ccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/hr/laptop-apple-macbook-air-13-3-retina-mgn63cr-a-octacore-apple-m1-8gb-256gb-ssd-apple-graphics-hr-tipkovnica-sivi-015800376' and (text() = 'više o proizvodu ' or . = 'više o proizvodu ')]</value>
      <webElementGuid>a11a0ef4-fd3e-4a64-9be4-4df31877c663</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
