<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_1</name>
   <tag></tag>
   <elementGuidId>42b8fb53-bb66-45f5-bd32-6fd9eaa23798</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='topcartlink']/a/div[3]/span/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.cart-qty</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c82a2d38-5d87-4f69-8f3a-64d44aad9063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cart-qty</value>
      <webElementGuid>2ae87633-4331-45b5-9ed5-8f7e0e6c8b27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6c842f93-8ef7-47d0-9113-25531e1f0e72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topcartlink&quot;)/a[@class=&quot;cartHolder&quot;]/div[@class=&quot;articleNum&quot;]/span[@class=&quot;outer&quot;]/span[@class=&quot;inner&quot;]/span[@class=&quot;cart-qty&quot;]</value>
      <webElementGuid>4f308aa0-22cc-4d28-8107-21125da958e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topcartlink']/a/div[3]/span/span/span</value>
      <webElementGuid>b38d1fd5-ce02-44d3-8100-dc62226fee2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kn'])[1]/following::span[4]</value>
      <webElementGuid>7f274253-e5fa-480c-b858-1e56e272ed6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Smartphone POCO M3 Pro 5G, 6.5', '&quot;', ', 4GB, 64GB, Android 11, crni')])[1]/preceding::span[1]</value>
      <webElementGuid>f9a1663d-10e0-4c91-bef5-57d539015257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(1.567,10 kn)'])[1]/preceding::span[2]</value>
      <webElementGuid>96a07ed9-2dc7-4b4a-8fd1-007f6220090a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1']/parent::*</value>
      <webElementGuid>709e6f17-a013-412c-acdb-66840bb44a49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span/span/span</value>
      <webElementGuid>c56c28aa-8e73-4a14-95db-6053a56e2fa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '1' or . = '1')]</value>
      <webElementGuid>4b5da97f-8e8e-4f97-95e1-9022540eae20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
