<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Akcije</name>
   <tag></tag>
   <elementGuidId>4a085fcd-9377-4ac6-9b5f-cbfe72bdef2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headerMenuParent']/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.submenuLink.akcije.submenuHover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>037ce2f5-a7cc-4233-be06-5292a25d8868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submenuLink akcije  submenuHover</value>
      <webElementGuid>7de167c3-88c7-4382-878a-bf1e8c8a5b86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/hr/discounted-products/informatika-01</value>
      <webElementGuid>bdb848fd-f9c5-49fd-a45b-07c37784b4c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Akcije</value>
      <webElementGuid>227b1024-9b59-45f3-814c-7294e070995f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Akcije</value>
      <webElementGuid>927ffc96-90f4-4942-81f6-cafde45b98a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;k-webkit k-webkit114 js no-touch svg inlinesvg svgclippaths&quot;]/body[@class=&quot;color-neutral notAndroid23&quot;]/div[@class=&quot;master-wrapper-page&quot;]/div[@id=&quot;headerMenuParent&quot;]/ul[@class=&quot;mega-menu&quot;]/li[@class=&quot;mega-menu-responsive-root-hide&quot;]/a[@class=&quot;submenuLink akcije  submenuHover&quot;]</value>
      <webElementGuid>da459fec-a2a9-4863-9f9a-acf693897904</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headerMenuParent']/ul/li/a</value>
      <webElementGuid>4ba69cf5-12cf-46bc-a9ce-c2b46150d954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Akcije')]</value>
      <webElementGuid>6ea0c99c-8c6d-4af1-97a9-31677455af4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/following::a[1]</value>
      <webElementGuid>fc047b0c-07cc-40aa-81e8-250682bcfee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal menu'])[1]/following::a[1]</value>
      <webElementGuid>d2518c2b-c2c4-4007-9bbd-2d9859fe8ca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Posebne ponude'])[1]/preceding::a[1]</value>
      <webElementGuid>84bccea2-2253-4e21-a4cc-963c4e60a892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Novo'])[1]/preceding::a[2]</value>
      <webElementGuid>4099790c-007d-4578-a079-a8ea3aae083f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Akcije']/parent::*</value>
      <webElementGuid>8ad2505c-e52d-4d97-8928-d925710428f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/hr/discounted-products/informatika-01')]</value>
      <webElementGuid>898b45e0-2673-45a8-b63e-2784bd604835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/ul/li/a</value>
      <webElementGuid>4d4269f9-5383-4cba-bad5-acf8c2b93a6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/hr/discounted-products/informatika-01' and @title = 'Akcije' and (text() = 'Akcije' or . = 'Akcije')]</value>
      <webElementGuid>bc9c93bb-2a5a-4634-ba41-56b6dbce2a68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
